# Generated by Django 2.2 on 2019-04-27 20:52

from django.db import migrations, models
import post.models
import post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190428_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=post.models.upload_file_path, validators=[post.validators.validate_file_extension]),
        ),
    ]
