# Generated by Django 2.2 on 2019-04-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20190428_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
