# Generated by Django 2.0.6 on 2019-05-29 13:13

from django.db import migrations, models
import post.models
import post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20190529_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, default='site/img/blogging.png', upload_to=post.models.upload_file_path, validators=[post.validators.validate_file_extension]),
        ),
    ]
