# Generated by Django 2.0.6 on 2019-05-31 05:49

from django.db import migrations, models
import post.models
import post.validators


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20190531_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, default='images/blog_cover.jpg', upload_to=post.models.upload_file_path, validators=[post.validators.validate_file_extension]),
        ),
    ]
